version: '3.1'

services:

  updateadcontrol:
    image: updateadcontrol:1.2
    hostname: updateadcontrol
    container_name: updateadcontrol
    environment:
      AD_SERVER: 
      USER_SVC: 
      PASS_SVC: 
      MYSQL_HOST: 
      MYSQL_USER: 
      MYSQL_PASS: 
      MYSQL_DB: 
    external_links:
      - mysql:mysql
    ports:
      - "5000:5000"
    networks:
      front:
        ipv4_address: 172.36.238.20

networks:
    front:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.36.238.0/24